apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: "https://github.com/<your-username>/k8s-production-blueprint.git"
  ref:
    branch: main
  secretRef:
    name: flux-system
